repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade
        args:
          - "--py37-plus"
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: '/mibs'
  - repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: '/mibs'
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: '/mibs'
        additional_dependencies: [
          flake8-docstrings,
          flake8-builtins,
          flake8-comprehensions,
          flake8-print,
          flake8-eradicate,
        ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
    -   id: mypy
        exclude: '/mibs'
#        args: [--strict]